== Client libraries for 10Duke Identity and Entitlement

Client libraries for .NET applications, for using services of the 10Duke Identity and Entitlement. Main features are:

* Querying user info
* Checking and consuming licenses
* Releasing consumed licenses
* Checking end-user permissions

.Client libraries
|===
|Package |Application type |.NET target framework 

|https://github.com/10Duke/10duke-dotnet-client/tree/master/Tenduke.Client.AspNetCore[Tenduke.Client.AspNetCore]
|Web / ASP.NET Core
|.NET Standard 2.0

|https://github.com/10Duke/10duke-dotnet-client/tree/master/Tenduke.Client.WPF[Tenduke.Client.WPF]
|Desktop / WPF
|.NET Framework 4.6.1

|https://github.com/10Duke/10duke-dotnet-client/tree/master/Tenduke.Client.WinForms[Tenduke.Client.WinForms]
|Desktop / WinForms
|.NET Framework 4.6.1
|===

All the client libraries are based on generic https://github.com/10Duke/10duke-dotnet-client/tree/master/Tenduke.Client[Tenduke.Client] base library, that can be used as a starting point for developing custom client libraries.

=== Installation

All the client libraries are distributed via NuGet. An example of installing the ASP.NET Core client library using NuGet Package Manager:

._Installation with NuGet PackageManager_
----
Install-Package Tenduke.Client.AspNetCore
----
