//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tenduke.Client.WPFSample.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://genco-dev.10duke.net/user/oauth20/authz")]
        public string AuthzUri {
            get {
                return ((string)(this["AuthzUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://genco-dev.10duke.net/user/oauth20/token")]
        public string TokenUri {
            get {
                return ((string)(this["TokenUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://genco-dev.10duke.net/user/info")]
        public string UserInfoUri {
            get {
                return ((string)(this["UserInfoUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SampleAppWPF")]
        public string ClientID {
            get {
                return ((string)(this["ClientID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ClientSecret {
            get {
                return ((string)(this["ClientSecret"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("oob:SampleApp")]
        public string RedirectUri {
            get {
                return ((string)(this["RedirectUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("openid profile email")]
        public string Scope {
            get {
                return ((string)(this["Scope"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StoreAuthorization {
            get {
                return ((bool)(this["StoreAuthorization"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowRememberMe {
            get {
                return ((bool)(this["ShowRememberMe"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowInsecureCerts {
            get {
                return ((bool)(this["AllowInsecureCerts"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA3IXrO+Np6fZE/xJmb1b/
CYvxF4BElNGeEOCpF0fMtQuJHDmCicGXlW9WRm6cDJ83kXDanibaKTkDPOWGDluk
4GweM0b28IhUZl6P31X7OTIAVJSGmsIPBfvWE7ECbHGOlzPU9E1i0AiB5E2BDh3J
Mb1Y6BKoEnb5gLSbxSfVOVsEhV+m9Wgrk5q/ONgitmh+Ghqt27bj66FXj9IdsYPa
06oPS9uE1onZLMhAwpI5XVowgU90EkUzpzXsF1SCSBIx7uS1xADpPIk1KFp+zlgC
+LibzRrJVh0yf5Xnkv6Fn7Ksv5543IfSBVKp86Xe18xNwvI5L9uYj45agTYkYxrN
1hCf2OUjyVEBuKhSZqV61R5MNAGw7/LQ31YkzmD2Pypd2COVuNyTcEHZ8iq/FzGz
HpKv3gEPriH+2UXYhRowJqtlq5+/9rTQwct+hjEfz4wH2iv0SHofhJvw6XmcBXjM
KFDi55OQpm7VvDEB172Q3mX0rkdTcWB6m2D39KXmVU9ymDGQxJZAW8vR87u94Amd
qyV7e+oAGFVtk1/ivDbC+yHNqiqrq7XrmigiNiym1J9yqSFrRX84XaCpIoGg6j00
7h2Q5/Eol6UULpzjlHOEVH1hxNNKqypfOVkQjpR+CWXWFoMWP1BvlFwKZieKiqNi
fZLpxsofUYpuym9Rx1+KHB8CAwEAAQ==
-----END PUBLIC KEY-----")]
        public string SignerKey {
            get {
                return ((string)(this["SignerKey"]));
            }
        }
    }
}
